#!/bin/sh

# ************************************************************************** */
# By:      N,Anucha <ana.cpe9@gmail.com>
# Created: 2024-05-15 by n,anucha
# Updated: 2024-05-15 by n,anucha
# ************************************************************************** */

LC_ALL=C

# kebab-case: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
# snake_case: ^([a-z][a-z0-9]*)(_[a-z0-9]+)*$
# UpperCamelCase: ^[A-Z][a-zA-Z0-9]+$
# lowerCamelCase: ^[a-z][a-zA-Z0-9]+$

valid_name="^(((\.)?[a-z][a-z0-9]*)((-|\.)[a-z0-9]+)*)(((\/)(\.)?[a-z][a-z0-9]*)((-|\.)[a-z0-9]+)*)*(_test\.go)?$"

for file in $(git diff --cached --name-only | grep -E '\.(go)$'); do
  if [[ ! $file =~ $valid_name ]]
  then
    echo "git: pre-commit, error: folders and filenames must be kebab-case only!"
    echo ">>> $file"
    exit 1
  fi
done

exit 0
